# Generated by Django 6.0.5 on 2026-06-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
